### ISSUE TITLE
Image no longer available on docker hub

### ISSUE THREAD

**Issue by palmithor** [webpack-contrib/circleci-node-jdk8#1]
Hey! 

I have been using your image in a project of mine for a while now but my build on circle-ci recently started failing and I figured out that it was because your image isn't available on docker hub anymore. Is there any reason why it has been removed? Do you expect to publish it again? 
https://hub.docker.com/r/webpackcontrib/circleci-node-jdk8/

**Comment by kalote** [comment]
+1000

**Comment by joshwiens** [comment]
https://github.com/webpack-contrib/circleci-jdk9-node8

Or in it's published form ...

https://hub.docker.com/u/webpackcontrib

Everything had to be moved under the org `webpackcontrib` as opposed to a user `webpackcontrib`. Docker hubs user & org management isn't the most well though service ever created.
